# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import hapi.rudder.rudder_pb2 as hapi_dot_rudder_dot_rudder__pb2


class ReleaseModuleServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Version = channel.unary_unary(
        '/hapi.services.rudder.ReleaseModuleService/Version',
        request_serializer=hapi_dot_rudder_dot_rudder__pb2.VersionReleaseRequest.SerializeToString,
        response_deserializer=hapi_dot_rudder_dot_rudder__pb2.VersionReleaseResponse.FromString,
        )
    self.InstallRelease = channel.unary_unary(
        '/hapi.services.rudder.ReleaseModuleService/InstallRelease',
        request_serializer=hapi_dot_rudder_dot_rudder__pb2.InstallReleaseRequest.SerializeToString,
        response_deserializer=hapi_dot_rudder_dot_rudder__pb2.InstallReleaseResponse.FromString,
        )
    self.DeleteRelease = channel.unary_unary(
        '/hapi.services.rudder.ReleaseModuleService/DeleteRelease',
        request_serializer=hapi_dot_rudder_dot_rudder__pb2.DeleteReleaseRequest.SerializeToString,
        response_deserializer=hapi_dot_rudder_dot_rudder__pb2.DeleteReleaseResponse.FromString,
        )
    self.RollbackRelease = channel.unary_unary(
        '/hapi.services.rudder.ReleaseModuleService/RollbackRelease',
        request_serializer=hapi_dot_rudder_dot_rudder__pb2.RollbackReleaseRequest.SerializeToString,
        response_deserializer=hapi_dot_rudder_dot_rudder__pb2.RollbackReleaseResponse.FromString,
        )
    self.UpgradeRelease = channel.unary_unary(
        '/hapi.services.rudder.ReleaseModuleService/UpgradeRelease',
        request_serializer=hapi_dot_rudder_dot_rudder__pb2.UpgradeReleaseRequest.SerializeToString,
        response_deserializer=hapi_dot_rudder_dot_rudder__pb2.UpgradeReleaseResponse.FromString,
        )
    self.ReleaseStatus = channel.unary_unary(
        '/hapi.services.rudder.ReleaseModuleService/ReleaseStatus',
        request_serializer=hapi_dot_rudder_dot_rudder__pb2.ReleaseStatusRequest.SerializeToString,
        response_deserializer=hapi_dot_rudder_dot_rudder__pb2.ReleaseStatusResponse.FromString,
        )


class ReleaseModuleServiceServicer(object):

  def Version(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InstallRelease(self, request, context):
    """InstallRelease requests installation of a chart as a new release.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteRelease(self, request, context):
    """DeleteRelease requests deletion of a named release.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RollbackRelease(self, request, context):
    """RollbackRelease rolls back a release to a previous version.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpgradeRelease(self, request, context):
    """UpgradeRelease updates release content.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReleaseStatus(self, request, context):
    """ReleaseStatus retrieves release status.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReleaseModuleServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Version': grpc.unary_unary_rpc_method_handler(
          servicer.Version,
          request_deserializer=hapi_dot_rudder_dot_rudder__pb2.VersionReleaseRequest.FromString,
          response_serializer=hapi_dot_rudder_dot_rudder__pb2.VersionReleaseResponse.SerializeToString,
      ),
      'InstallRelease': grpc.unary_unary_rpc_method_handler(
          servicer.InstallRelease,
          request_deserializer=hapi_dot_rudder_dot_rudder__pb2.InstallReleaseRequest.FromString,
          response_serializer=hapi_dot_rudder_dot_rudder__pb2.InstallReleaseResponse.SerializeToString,
      ),
      'DeleteRelease': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteRelease,
          request_deserializer=hapi_dot_rudder_dot_rudder__pb2.DeleteReleaseRequest.FromString,
          response_serializer=hapi_dot_rudder_dot_rudder__pb2.DeleteReleaseResponse.SerializeToString,
      ),
      'RollbackRelease': grpc.unary_unary_rpc_method_handler(
          servicer.RollbackRelease,
          request_deserializer=hapi_dot_rudder_dot_rudder__pb2.RollbackReleaseRequest.FromString,
          response_serializer=hapi_dot_rudder_dot_rudder__pb2.RollbackReleaseResponse.SerializeToString,
      ),
      'UpgradeRelease': grpc.unary_unary_rpc_method_handler(
          servicer.UpgradeRelease,
          request_deserializer=hapi_dot_rudder_dot_rudder__pb2.UpgradeReleaseRequest.FromString,
          response_serializer=hapi_dot_rudder_dot_rudder__pb2.UpgradeReleaseResponse.SerializeToString,
      ),
      'ReleaseStatus': grpc.unary_unary_rpc_method_handler(
          servicer.ReleaseStatus,
          request_deserializer=hapi_dot_rudder_dot_rudder__pb2.ReleaseStatusRequest.FromString,
          response_serializer=hapi_dot_rudder_dot_rudder__pb2.ReleaseStatusResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hapi.services.rudder.ReleaseModuleService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
